# Generated by Django 4.0.6 on 2024-03-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='projeto_imagens/'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='repositorio_github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='video_youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
