# Generated by Django 4.0.6 on 2024-04-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0002_alter_projeto_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='ficheiro_projeto',
            field=models.FileField(blank=True, null=True, upload_to='ficheiros_projeto/'),
        ),
    ]
