# Generated by Django 4.0.6 on 2024-05-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0003_projeto_ficheiro_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linguagemprogramacao',
            name='disciplina',
            field=models.ManyToManyField(blank=True, to='portefolio.disciplina'),
        ),
        migrations.AlterField(
            model_name='linguagemprogramacao',
            name='projeto',
            field=models.ManyToManyField(blank=True, to='portefolio.projeto'),
        ),
    ]
