# Generated by Django 4.0.6 on 2024-04-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivais', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='posicao',
        ),
        migrations.AddField(
            model_name='festival',
            name='posicao',
            field=models.ManyToManyField(to='festivais.localizacao'),
        ),
    ]
