# Generated by Django 4.0.6 on 2024-03-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='ano',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='banda',
            name='nacionalidade',
            field=models.CharField(default='trocar', max_length=100),
        ),
        migrations.AddField(
            model_name='musica',
            name='ano',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='musica',
            name='duracao',
            field=models.IntegerField(default=1),
        ),
    ]
