# Generated by Django 4.0.6 on 2024-04-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0002_banda_ano_banda_nacionalidade_musica_ano_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='titulo',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='musica',
            old_name='titulo',
            new_name='nome',
        ),
    ]
