# Generated by Django 4.0.6 on 2024-05-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0003_rename_titulo_album_nome_rename_titulo_musica_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='biografia',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='letra',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
